server:
  port: 2000
  server:
    compression:
      enabled: true
      excluded-user-agents: gozilla,traviata
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 512

spring:
  application:
    name: gateway-service
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    password: redis@com
  cloud:
# https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user-service:2100
          predicates:
            - Path=/user/**
        - id: order
          uri: lb://order-service:2300
          predicates:
            - Path=/order/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#  zipkin:
#    base-url: http://zipkin.server:30774/
#  sleuth:
#    sampler:
#      percentage: 1.0


# Log
logging:
  file:
    path: logs/intecsec/springcloud/alibaba/${spring.application.name}
  level:
    org:
      springframework: INFO
    com:
      intecsec: DEBUG

# feign
feign:
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 512
    response:
      enabled: true