spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intecsec_mall_order?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: dev.nacos.intecsec.com:8848
    sentinel:
      transport:
        port: 2301
        dashboard: localhost:8080
      eager: true
